name: Deploy to Server

on:
  push:
    branches:
      - master

jobs:
  run_pull:
    name: Pull from GitHub
    runs-on: ubuntu-latest
    env:
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      SSH_USER: ${{ secrets.SSH_USER }}
      SSH_HOST: ${{ secrets.SSH_HOST }}
      WORK_DIR: ${{ secrets.WORK_DIR }}
      MAIN_BRANCH: ${{ secrets.MAIN_BRANCH }}
    steps:
      - name: install ssh key
        run: |
          install -m 600 -D /dev/null ~/.ssh/id_rsa
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
      - name: connect and pull
        run: ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "cd ${{ secrets.WORK_DIR }} && git checkout ${{ secrets.MAIN_BRANCH }} && git pull"
      - name: cleanup
        run: rm -rf ~/.ssh

  build:
    name: build
    needs: run_pull
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code (you might need this if not already checked out)
        uses: actions/checkout@v3
      - name: Show Node.js and npm versions
        run: |
          node -v
          npm -v
      - name: Install dependencies
        run: npm install
      - name: List node_modules directory
        run: ls -al node_modules
      - name: Run build script
        run: npm run build
      - name: List build output (if applicable)
        run: ls -al ${{ secrets.WORK_DIR }}
