name: Deploy to Server

on:
  push:
    branches:
      - master

jobs:
  run_pull:
    name: pull
    runs-on: ubuntu-latest
    env:
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      SSH_USER: ${{ secrets.SSH_USER }}
      SSH_HOST: ${{ secrets.SSH_HOST }}
      WORK_DIR: ${{ secrets.WORK_DIR }}
      MAIN_BRANCH: ${{ secrets.MAIN_BRANCH }}
      NAME_DIR: basreng-ui
    steps:
      - name: install ssh key
        run: |
          install -m 600 -D /dev/null ~/.ssh/id_rsa
          echo "${{ env.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          ssh-keyscan -H ${{ env.SSH_HOST }} >> ~/.ssh/known_hosts
      - name: connect and pull
        run: ssh ${{ env.SSH_USER }}@${{ env.SSH_HOST }} "cd ${{ env.WORK_DIR }} && git checkout ${{ env.MAIN_BRANCH }} && git pull"
      - name: cleanup
        run: rm -rf ~/.ssh

  build:
    name: build
    needs: run_pull
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code (you might need this if not already checked out)
        uses: actions/checkout@v3
      - name: Show Node.js and npm versions
        run: |
          node -v
          npm -v
      - name: Install dependencies
        run: npm install
      - name: Run build script
        run: npm run build

  deploy:
    name: deploy
    needs: run_pull
    runs-on: ubuntu-latest
    steps:
      - name: deploy with PM2
        run: pm2 list
      
