name: Deploy to Server

on:
  push:
    branches:
      - master

env:
  SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
  SSH_USER: ${{ secrets.SSH_USER }}
  SSH_HOST: ${{ secrets.SSH_HOST }}
  WORK_DIR: ${{ secrets.WORK_DIR }}
  MAIN_BRANCH: ${{ secrets.MAIN_BRANCH }}
  NAME_DIR: basreng-ui

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - name: deploy with PM2 via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ env.SSH_HOST }}
          username: ${{ env.SSH_USER }}
          key: ${{ env.SSH_PRIVATE_KEY }}
          script: |
            cd ${{ env.WORK_DIR }}
            git fetch --all
            git checkout ${{ env.MAIN_BRANCH }}
            git pull
            npm run build
            pm2 restart ${{ env.NAME_DIR }}
      - name: cleanup
        run: rm -rf ~/.ssh